-- ═════════════════════════════════════════════════════════════
-- STUDYRIA ADRE DRIVER ROAD TRANSPORT PRACTICE SET — REGISTRY SEED
-- Run AFTER brainlab-tests-v3-migration.sql.
-- Registers 138 Road Transport practice questions (series-scoped
-- to 'adre-g3-driver') with status='needs_review'. NONE are public until
-- the owner approves them in Admin → Test Engine. is_pyq=false.
-- ═════════════════════════════════════════════════════════════
INSERT INTO public.bl_question_registry
  (qhash, series_id, subject, topic, status, source, source_type, is_pyq)
VALUES
('7ecf2929','adre-g3-driver','Road Transport','Documents & Licence','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('307553a4','adre-g3-driver','Road Transport','Documents & Licence','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('aee2d135','adre-g3-driver','Road Transport','Documents & Licence','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('22ee7ac5','adre-g3-driver','Road Transport','Documents & Licence','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('f09a5301','adre-g3-driver','Road Transport','Documents & Licence','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('0e75e0aa','adre-g3-driver','Road Transport','Documents & Licence','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('b6879252','adre-g3-driver','Road Transport','Documents & Licence','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('436030a4','adre-g3-driver','Road Transport','Documents & Licence','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('5c13ae80','adre-g3-driver','Road Transport','Documents & Licence','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('1bbd7e51','adre-g3-driver','Road Transport','Documents & Licence','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('6e58123d','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('fd210e67','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('ddcf01e4','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('36a82708','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('4bbf1336','adre-g3-driver','Road Transport','First Aid','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('2bb13eed','adre-g3-driver','Road Transport','First Aid','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('08784ac9','adre-g3-driver','Road Transport','First Aid','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('8e8e4765','adre-g3-driver','Road Transport','First Aid','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('cad002b7','adre-g3-driver','Road Transport','First Aid','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('46781392','adre-g3-driver','Road Transport','First Aid','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('472b5822','adre-g3-driver','Road Transport','Traffic Signs','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('502d787a','adre-g3-driver','Road Transport','Traffic Signs','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('13ce8f61','adre-g3-driver','Road Transport','Traffic Signs','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('bf3c6a76','adre-g3-driver','Road Transport','Traffic Signs','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('3f0b1335','adre-g3-driver','Road Transport','Traffic Signs','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('c5c964da','adre-g3-driver','Road Transport','Traffic Signs','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('8e07e478','adre-g3-driver','Road Transport','Traffic Signs','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('1f3be146','adre-g3-driver','Road Transport','Traffic Signs','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('bb9f1258','adre-g3-driver','Road Transport','Road Markings','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('3f55c3ec','adre-g3-driver','Road Transport','Road Markings','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('ffe65118','adre-g3-driver','Road Transport','Road Markings','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('eeb2dd37','adre-g3-driver','Road Transport','Road Markings','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('c1e1f4ab','adre-g3-driver','Road Transport','Road Markings','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('653f5b03','adre-g3-driver','Road Transport','Road Markings','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('e30060b6','adre-g3-driver','Road Transport','Signals','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('8256b7e2','adre-g3-driver','Road Transport','Signals','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('41b56f27','adre-g3-driver','Road Transport','Signals','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('457d6236','adre-g3-driver','Road Transport','Signals','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('a2280c02','adre-g3-driver','Road Transport','Rules of the Road','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('5d4b131c','adre-g3-driver','Road Transport','Rules of the Road','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('8d5f5d55','adre-g3-driver','Road Transport','Rules of the Road','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('5cb6b9f0','adre-g3-driver','Road Transport','Rules of the Road','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('33d15e45','adre-g3-driver','Road Transport','Rules of the Road','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('4cd2b2a4','adre-g3-driver','Road Transport','Parking','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('b3b2b01e','adre-g3-driver','Road Transport','Parking','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('30cfc68e','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('447a83b6','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('90365e14','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('1c6b7688','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('5ed22c04','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('4c285d67','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('fa692a77','adre-g3-driver','Road Transport','Vehicle Systems','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('72cdcf61','adre-g3-driver','Road Transport','Vehicle Systems','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('fbbc736b','adre-g3-driver','Road Transport','Vehicle Systems','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('de76ea4e','adre-g3-driver','Road Transport','Vehicle Systems','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('34dbf31a','adre-g3-driver','Road Transport','Vehicle Systems','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('b9b379d4','adre-g3-driver','Road Transport','Vehicle Systems','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('9a7ed07e','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('07b57fde','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('04624164','adre-g3-driver','Road Transport','Rules of the Road','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('9398a94d','adre-g3-driver','Road Transport','Rules of the Road','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('adca1bc4','adre-g3-driver','Road Transport','Rules of the Road','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('3ae31be4','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('b141cc8f','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('88bfbafc','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('35736414','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('074590a9','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('eda1a881','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('4e51c193','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('faf14ec1','adre-g3-driver','Road Transport','Emission Norms','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('da0bb95c','adre-g3-driver','Road Transport','Eco Driving','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('2353cdf1','adre-g3-driver','Road Transport','Eco Driving','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('9c52ddde','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('a9661510','adre-g3-driver','Road Transport','Maintenance','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('5c51999a','adre-g3-driver','Road Transport','Maintenance','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('9cc3abe3','adre-g3-driver','Road Transport','Maintenance','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('0f78e8f2','adre-g3-driver','Road Transport','Maintenance','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('3dde56bc','adre-g3-driver','Road Transport','Maintenance','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('b4079806','adre-g3-driver','Road Transport','Maintenance','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('17da143e','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('8e751d1f','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('e8a3f585','adre-g3-driver','Road Transport','Vehicle Systems','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('62520c6c','adre-g3-driver','Road Transport','Lights','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('81293937','adre-g3-driver','Road Transport','Lights','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('91c643f9','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('283cfad4','adre-g3-driver','Road Transport','Two-Wheeler Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('7d42dc4b','adre-g3-driver','Road Transport','Two-Wheeler Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('26bd464e','adre-g3-driver','Road Transport','Two-Wheeler Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('dfe758ac','adre-g3-driver','Road Transport','Two-Wheeler Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('e70a975b','adre-g3-driver','Road Transport','Permits','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('267d10d6','adre-g3-driver','Road Transport','Permits','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('6ff4c1e6','adre-g3-driver','Road Transport','Permits','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('3f91e2e5','adre-g3-driver','Road Transport','Legal','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('0300aa6d','adre-g3-driver','Road Transport','Legal','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('357c0390','adre-g3-driver','Road Transport','First Aid','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('55370cbf','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('2d325ba6','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('ac9198a9','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('7a71902c','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('971f6d4f','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('4107f594','adre-g3-driver','Road Transport','Rules of the Road','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('ce252f37','adre-g3-driver','Road Transport','Rules of the Road','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('41490991','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('ab0b6ee1','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('49e871b4','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('1ea30141','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('689ac8c4','adre-g3-driver','Road Transport','Legal','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('29ff9648','adre-g3-driver','Road Transport','Road Markings','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('aac90b80','adre-g3-driver','Road Transport','Road Markings','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('dbd79ce7','adre-g3-driver','Road Transport','Rules of the Road','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('b5c6b40a','adre-g3-driver','Road Transport','Traffic Signs','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('5fe407fa','adre-g3-driver','Road Transport','Traffic Signs','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('5900b83c','adre-g3-driver','Road Transport','Traffic Signs','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('3fc98700','adre-g3-driver','Road Transport','Rules of the Road','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('7fd2008e','adre-g3-driver','Road Transport','Rules of the Road','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('a4e166e1','adre-g3-driver','Road Transport','Rules of the Road','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('8063e6ee','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('84bb70ef','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('9205ab0f','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('eb4f1fa6','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('758c2cba','adre-g3-driver','Road Transport','Two-Wheeler Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('67d4c843','adre-g3-driver','Road Transport','Two-Wheeler Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('40dfe2f4','adre-g3-driver','Road Transport','Two-Wheeler Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('54c89c87','adre-g3-driver','Road Transport','Two-Wheeler Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('af11a4fc','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('99f9056b','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('4c9b5d07','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('e4a8d5a5','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('e4592f82','adre-g3-driver','Road Transport','Rules of the Road','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('7ef3af4a','adre-g3-driver','Road Transport','Documents & Licence','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('d20bf564','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('abc8ceac','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('f58e712c','adre-g3-driver','Road Transport','Safety','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('97216e76','adre-g3-driver','Road Transport','Driving Practice','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('4d767e20','adre-g3-driver','Road Transport','First Aid','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('a3419207','adre-g3-driver','Road Transport','First Aid','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('80ff9cb8','adre-g3-driver','Road Transport','First Aid','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false),
('123a7d4e','adre-g3-driver','Road Transport','First Aid','needs_review','Studyria ADRE Driver practice set — AI-authored practice MCQ (MV Act 1988 / road safety), human review required','practice',false)
ON CONFLICT (qhash) DO NOTHING;
