-- ═════════════════════════════════════════════════════════════════
-- STUDYRIA VFA PRACTICE SET 1 — QUESTION REGISTRY SEED (v3, Sep 2026)
-- Run AFTER brainlab-tests-v3-migration.sql.
-- Registers the 217 VFA practice questions (vfa-practice-pool.js)
-- with status='needs_review'. NONE are public until the owner reviews and
-- approves them in Admin → Test Engine. AI authorship is disclosed in
-- source; is_pyq=false — these are PRACTICE questions, never PYQs.
-- ═════════════════════════════════════════════════════════════════
INSERT INTO public.bl_question_registry
  (qhash, series_id, subject, topic, status, source, source_type, is_pyq)
VALUES
('49325e94','vfa','Biology','Cell Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('be0abc0d','vfa','Biology','Plant Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('9f4d8f30','vfa','Biology','Cell Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('bfd27988','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('389594ae','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('b18e86ae','vfa','Biology','Nutrition','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('4f9496c3','vfa','Biology','Human Health','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('33622ce4','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('cba2b352','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('52789c48','vfa','Biology','Genetics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('379c08df','vfa','Biology','Genetics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('85af1f90','vfa','Biology','Plant Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('dd5b33ff','vfa','Biology','Plant Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('e0857584','vfa','Biology','Plant Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('12b9e9ad','vfa','Biology','Cell Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('8f3032bf','vfa','Biology','Cell Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('470996cf','vfa','Biology','Plant Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('57a6c26b','vfa','Biology','Plant Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('08f67221','vfa','Biology','Reproduction','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('7e12657f','vfa','Biology','Plant Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('8d193380','vfa','Biology','Diseases','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('e5ef4090','vfa','Biology','Diseases','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('b5576258','vfa','Biology','Diseases','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('6d65892c','vfa','Biology','Microbiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('60301afe','vfa','Biology','Immunity','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('e7e3ffd5','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('e2297bc1','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('84619ca5','vfa','Biology','Nutrition','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('608e5cdc','vfa','Biology','Human Health','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('2e6edde0','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('d6527f66','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('c6d43ffb','vfa','Biology','Reproduction','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('fedf16b9','vfa','Biology','Genetics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('d28a9414','vfa','Biology','Genetics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('130c2446','vfa','Biology','Evolution','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('ce172e9b','vfa','Biology','Animal Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('7f2dfdf0','vfa','Biology','Animal Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('5b8f2fa5','vfa','Biology','Animal Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('ce498d2b','vfa','Biology','Animal Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('50885b9d','vfa','Biology','Animal Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('c868b7f3','vfa','Biology','Ecology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('f61dc005','vfa','Biology','Ecology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('e9d15b1d','vfa','Biology','Ecology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('a8861db6','vfa','Biology','Environment','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('63ebd79e','vfa','Biology','Environment','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('f93e5e10','vfa','Biology','Biodiversity','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('568325eb','vfa','Biology','Biodiversity','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('9e87aae5','vfa','Biology','Biodiversity','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('9bcfe9f6','vfa','Biology','Biodiversity','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('847d6bb0','vfa','Biology','Ecology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('b8aeb8d5','vfa','Biology','Ecology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('24b45687','vfa','Biology','Diseases','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('54184f10','vfa','Biology','Diseases','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('7eb9764d','vfa','Biology','Diseases','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('d96d3817','vfa','Biology','Diseases','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('4f6786cb','vfa','Biology','Microbiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('4759b478','vfa','Biology','Microbiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('dba3f737','vfa','Biology','Diseases','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('1bbc03da','vfa','Biology','Life Processes','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('9818c52b','vfa','Biology','Life Processes','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('9f55e048','vfa','Biology','Life Processes','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('a4b62ce6','vfa','Biology','Plant Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('6a38da5c','vfa','Biology','Plant Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('b6eff307','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('c4036a9e','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('b36743b3','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('6de46e00','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('8bdf982d','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('c510f563','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('9a713767','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('ec372019','vfa','Biology','Human Health','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('c382780d','vfa','Biology','Genetics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('9f725d7d','vfa','Biology','Genetics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('82dc5041','vfa','Biology','Genetics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('bbe66b0d','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('1e5b833a','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('1b2803cf','vfa','Biology','Human Physiology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('c93eb5d7','vfa','Biology','Ecology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('d6a99683','vfa','Biology','Ecology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('c782f3b2','vfa','Biology','Environment','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('1b7c5bd4','vfa','Biology','Environment','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('2bd101e0','vfa','Biology','Environment','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('a6d8310b','vfa','Biology','Environment','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('bc7c1030','vfa','Biology','Environment','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('6091c2e8','vfa','Biology','Biodiversity','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('c10c0dbe','vfa','Biology','Animal Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('18ad6c8c','vfa','Biology','Human Health','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('9a0d1ace','vfa','Biology','Evolution','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('5bcfe471','vfa','Biology','Animal Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('7374bed4','vfa','Biology','Animal Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('b32854cf','vfa','Biology','Cell Biology','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('fb56a527','vfa','Chemistry','Everyday Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('8dc8541d','vfa','Chemistry','Everyday Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('55fe7321','vfa','Chemistry','Everyday Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('14c80fe6','vfa','Chemistry','Everyday Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('c2169345','vfa','Chemistry','Acids and Bases','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('cfab4ea4','vfa','Chemistry','Everyday Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('8c884905','vfa','Chemistry','Everyday Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('9522f14d','vfa','Chemistry','Everyday Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('b61b3cb6','vfa','Chemistry','Everyday Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('ad832884','vfa','Chemistry','Everyday Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('968c78e5','vfa','Chemistry','Periodic Table','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('fa6e9ec1','vfa','Chemistry','Atomic Structure','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('5d25b81e','vfa','Chemistry','Atomic Structure','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('518a0890','vfa','Chemistry','Atomic Structure','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('bdc9bddd','vfa','Chemistry','Atomic Structure','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('1c52af2e','vfa','Chemistry','Atomic Structure','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('2d953c0d','vfa','Chemistry','Atomic Structure','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('efb72044','vfa','Chemistry','Atomic Structure','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('eb6739f7','vfa','Chemistry','Periodic Table','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('15a0b60c','vfa','Chemistry','Periodic Table','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('b4f0ef7d','vfa','Chemistry','Periodic Table','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('acc7f2e7','vfa','Chemistry','Periodic Table','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('77d654aa','vfa','Chemistry','Periodic Table','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('190bc229','vfa','Chemistry','Chemical Bonding','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('15cdf377','vfa','Chemistry','Chemical Bonding','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('77eeed9b','vfa','Chemistry','Chemical Bonding','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('50bf08ea','vfa','Chemistry','Chemical Bonding','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('279339b3','vfa','Chemistry','Carbon Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('e8f501b9','vfa','Chemistry','Chemical Reactions','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('6c34ead0','vfa','Chemistry','Chemical Reactions','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('3d86fe17','vfa','Chemistry','Stoichiometry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('d164131c','vfa','Chemistry','Mole Concept','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('57af490b','vfa','Chemistry','Mole Concept','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('01816e3d','vfa','Chemistry','Atomic Structure','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('06564edf','vfa','Chemistry','Thermodynamics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('1d205073','vfa','Chemistry','Chemical Reactions','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('12befa9b','vfa','Chemistry','Equilibrium','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('4a6a0068','vfa','Chemistry','Redox','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('e929a026','vfa','Chemistry','Redox','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('6cb105cc','vfa','Chemistry','Redox','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('b137834f','vfa','Chemistry','Everyday Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('8b88f55c','vfa','Chemistry','Everyday Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('f1c398e8','vfa','Chemistry','Hydrocarbons','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('ddac044d','vfa','Chemistry','Hydrocarbons','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('217276d9','vfa','Chemistry','Alcohols','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('8d63418a','vfa','Chemistry','Carboxylic Acids','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('ec2ca151','vfa','Chemistry','Carboxylic Acids','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('0607337e','vfa','Chemistry','Alcohols','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('e01664dc','vfa','Chemistry','Carbon Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('54a78ac9','vfa','Chemistry','Environment','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('991139af','vfa','Chemistry','Everyday Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('8194cd32','vfa','Chemistry','Everyday Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('3228c0fa','vfa','Chemistry','Everyday Chemistry','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('31dbe0e1','vfa','Chemistry','Chemical Reactions','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('b018a5c9','vfa','Chemistry','Matter','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('e6df412d','vfa','Chemistry','Solutions','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('fdf19440','vfa','Chemistry','Solutions','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('975a85cf','vfa','Chemistry','Separation','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('98731933','vfa','Physics','Newton's Laws','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('9a954352','vfa','Physics','Work and Power','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('50579d0e','vfa','Physics','Work and Power','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('f2e6aa13','vfa','Physics','Electricity','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('0a68bd95','vfa','Physics','Waves','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('0c93afea','vfa','Physics','Force and Pressure','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('e3a94b8e','vfa','Physics','Optics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('a17a7395','vfa','Physics','Optics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('1b65c100','vfa','Physics','Sound','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('3724c7df','vfa','Physics','Sound','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('0523c25a','vfa','Physics','Optics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('9282e265','vfa','Physics','Optics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('1dc73427','vfa','Physics','Optics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('cee8a34e','vfa','Physics','Optics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('11a3629c','vfa','Physics','Optics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('50e91f30','vfa','Physics','Optics','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('a02fc4b6','vfa','Physics','Electricity','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('d652b57f','vfa','Physics','Electricity','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('a1b7d29e','vfa','Physics','Electricity','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('f34c4a54','vfa','Physics','Electricity','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('b879c563','vfa','Physics','Magnetism','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('465283ff','vfa','Physics','Magnetism','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('833c5961','vfa','Physics','Electricity','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('7649fe86','vfa','Physics','Magnetism','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('6a474566','vfa','Physics','Magnetism','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('5b35cb1e','vfa','Physics','Magnetism','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('66dc14c7','vfa','Physics','Magnetism','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('dbca06ac','vfa','Physics','Electricity','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('da653904','vfa','Physics','Electricity','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('4c8ad107','vfa','Physics','Newton's Laws','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('ea883cc7','vfa','Physics','Newton's Laws','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('03f18bce','vfa','Physics','Newton's Laws','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('19a38584','vfa','Physics','Newton's Laws','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('9ae9ceb5','vfa','Physics','Newton's Laws','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('df036406','vfa','Physics','Momentum','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('1564cae7','vfa','Physics','Momentum','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('3d917a3d','vfa','Physics','Momentum','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('d8844bda','vfa','Physics','Work and Power','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('4fc48695','vfa','Physics','Work and Power','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('320d9aca','vfa','Physics','Work and Power','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('f2bb39dd','vfa','Physics','Gravitation','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('1ee0421e','vfa','Physics','Gravitation','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('4ce33eda','vfa','Physics','Gravitation','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('2fa27a61','vfa','Physics','Gravitation','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('e7de4dc1','vfa','Physics','Space','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('f97179b5','vfa','Physics','Space','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('5754459f','vfa','Physics','Heat','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('ccff034e','vfa','Physics','Heat','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('4b964fc0','vfa','Physics','Heat','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('aeda9e56','vfa','Physics','Heat','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('6f0e36bd','vfa','Physics','Heat','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('926d658c','vfa','Physics','Heat','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('718ad6f8','vfa','Physics','Heat','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('4473394c','vfa','Physics','Pressure','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('2181447f','vfa','Physics','Sound','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('4c92ea2e','vfa','Physics','Sound','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('fe2ac58a','vfa','Physics','Sound','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('93a0ff7f','vfa','Physics','Sound','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('23a16801','vfa','Physics','Waves','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('715eb60f','vfa','Physics','Sound','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('ba2d01f0','vfa','Physics','Motion','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('c42329ad','vfa','Physics','Motion','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('5ab0e52f','vfa','Physics','Motion','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('e2e78467','vfa','Physics','Motion','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('df3beb4a','vfa','Physics','Motion','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('0c409fda','vfa','Physics','Motion','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('a51f1323','vfa','Physics','Electricity','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false),
('d1371e6d','vfa','Physics','Work and Power','needs_review','Studyria VFA practice set 1 — AI-authored practice MCQ (NCERT level), human review required before approval','practice',false)
ON CONFLICT (qhash) DO NOTHING;
